// Auto-generated by scripts/generate-portfolio-data.mjs — DO NOT EDIT

export interface PortfolioProject {
  id: string;
  title: string;
  slug: string;
  location: string;
  description: string;
  category: string;
  coverImage: string;
  galleryImages: string[];
}

const projects: PortfolioProject[] = [];

export function getAllProjects(): PortfolioProject[] {
  return projects;
}

export function getProjectBySlug(slug: string): PortfolioProject | null {
  return projects.find((p) => p.slug === slug) ?? null;
}

export function getRelatedProjects(slug: string, count = 3): PortfolioProject[] {
  return projects.filter((p) => p.slug !== slug).slice(0, count);
}
